### ISSUE TITLE
{BUG} CONTRIBUTE.md is out of date

### ISSUE THREAD

**Issue by LinuxGamer** [LinuxGamer/Universe#1]
CONTRIBUTE.md has the details for a C++ app rather than Python.

Good First Issue - Simple fix that is good for first time open source contributers

**Comment by dhruvdabhi101** [comment]
I would like to start my open source journey with this issue. Can I work on this issue ?

**Comment by dhruvdabhi101** [comment]
```diff
- g++ -o Universe main.cpp
+ python main.py
```

**Comment by dhruvdabhi101** [comment]
> ```diff
> - g++ -o Universe main.cpp
> + python main.py
> ```

is this okay ?

**Comment by LinuxGamer** [comment]
> > ```diff
> > - g++ -o Universe main.cpp
> > + python main.py
> > ```
> 
> is this okay ?

sorry I missed this, yes if you could change the "python" to "python3" that would be awesome

**Comment by LinuxGamer** [comment]
> I would like to start my open source journey with this issue. Can I work on this issue ?

sure thing, i've assinged you to it

**Comment by dhruvdabhi101** [comment]
and besides this.. anything else do i have to change ?

**Comment by LinuxGamer** [comment]
so it should just be "git clone", then the "python3 main.py" so all (apart from those bits and the "First Contributor" bit

**Comment by dhruvdabhi101** [comment]
i didn't understand the part which you have written in brackets. Can you please explain that ?

**Comment by dhruvdabhi101** [comment]
> i didn't understand the part which you have written in brackets. Can you please explain that ?

I just have to change c++ to python3 that's it.. okay ?

**Comment by LinuxGamer** [comment]
yes

**Comment by LinuxGamer** [comment]
anything to do with C++ compiling and running, needs to be removed

**Comment by dhruvdabhi101** [comment]
okay.. thank you sir. and After doing that.. I will create PR. Will that be okay ?

**Comment by LinuxGamer** [comment]
Yes, 100% - if you could mention this issue in the PR description by typing "#1" that would be amazing, thank you

**Comment by LinuxGamer** [comment]
Thank you very much @dhruvdabhi101 - You've made it onto the contributor's list as well, if you want you can join the discord, link at the bottom of the README

**Comment by dhruvdabhi101** [comment]
> Thank you very much @dhruvdabhi101 - You've made it onto the contributor's list as well, if you want you can join the discord, link at the bottom of the README

Sure Sir.
