### ISSUE TITLE
Add CONTRIBUTING.md file and PULL_REQUEST template

### ISSUE THREAD

**Issue by theritikchoure** [LinuxGamer/Universe#6]
Complete these community standards to get more traction on your repository.

![image](https://user-images.githubusercontent.com/56495602/198702644-1b391157-2164-4027-9511-dbd207849f6e.png)

**Comment by LinuxGamer** [comment]
Awesome, I've added CONTRIBUTING.md. Idk whether you'd like to do the PR templates, if not, I'll do them next time I'm at my PC

**Comment by theritikchoure** [comment]
I will add the PR templates ✨
